### ISSUE TITLE
`simplistic_editor` has a broken `TextEditingDeltaHistoryManager` implementation

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#1324]
The `TextEditingDeltaHistoryManager` has an interesting problem. The `updateShouldNotify` implementation looks sane:

```dart
  @override
  bool updateShouldNotify(TextEditingDeltaHistoryManager oldWidget) {
    return textEditingDeltaHistory != oldWidget.textEditingDeltaHistory;
  }
```
But it is broken by the fact that the `List<TextEditingDelta>` is constructed as a final mutable list in `_MyHomePageState`:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final ReplacementTextEditingController _replacementTextEditingController =
      ReplacementTextEditingController(
    text: 'The quick brown fox jumps over the lazy dog.',
  );
  final FocusNode _focusNode = FocusNode();
  final Set<ToggleButtonsState> _isSelected = {};
  final List<TextEditingDelta> _textEditingDeltaHistory = [];
```

However, fixing this with `DeepCollectionEquality` like [this](https://github.com/flutter/samples/commit/031a97ba6abf42526e14798930ed63b789a93d76) results in issues like the following when attempting to add text to the text field:

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following LateError was thrown building Container(bg: BoxDecoration(border:
Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid)), borderRadius:
BorderRadius.circular(4.0))):
LateInitializationError: Field 'toggleButtonStateManager' has already been
initialized.

The relevant error-causing widget was:
  Container
  Container:file:///Users/brettmorgan/Documents/GitHub/samples/simplistic_editor/lib/
  basic_text_field.dart:151:18

When the exception was thrown, this was the stack:
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:194:5)
#1      BasicTextInputClientState.toggleButtonStateManager= (package:simplistic_editor/basic_text_input_client.dart:46:40)
#2      BasicTextInputClientState.didChangeDependencies (package:simplistic_editor/basic_text_input_client.dart:61:5)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4974:13)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#60     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#64     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#70     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#71     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#76     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#80     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#91     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#101    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#103    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#111    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#120    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#123    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#125    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#128    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#130    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#131    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#132    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#133    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#134    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#135    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#139    _invoke (dart:ui/hooks.dart:151:10)
#140    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#141    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

═════════════════════════════════════════════════════════════════════════════════════
═══════════════
```

Please see #1357 for the support code for this issue.

**Comment by Renzo-Olivares** [comment]
I'll check this out. Thanks for bringing it on my radar!
