### ISSUE TITLE
Cannot run `app_to_app/android_view` sample on Android after upgrading to 3.7 

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/samples#1594]
1. Upgrade local flutter to 3.7 with `flutter upgrade`
2. Go to `add_to_app/android_view/flutter_module_using_plugin`
3. Connect Android device to computer
4. Run `flutter run`
5. See the following error:

```
"build/host/outputs/apk/app-debug.apk" does not exist.
```

- `flutter clean` does not do the trick
- I cannot reproduce this issue creating a project from scratch.
- Works on 3.3.10

Full log:

<details><summary>Full Log</summary>

Content was too long for GitHub, full here: [out.txt](https://github.com/flutter/samples/files/10501031/out.txt)

```
[        ] :url_launcher_android:bundleDebugAar (Thread[Execution worker Thread 9,5,main]) started.
[        ] producer locations for task group 0 (Thread[Execution worker Thread 5,5,main]) started.
[        ] producer locations for task group 0 (Thread[Execution worker Thread 5,5,main]) completed. Took 0.0 secs.
[        ] > Task :url_launcher_android:bundleDebugAar UP-TO-DATE
[        ] Caching disabled for task ':url_launcher_android:bundleDebugAar' because:
[        ]   Build cache is disabled
[        ] Skipping task ':url_launcher_android:bundleDebugAar' as it is up-to-date.
[        ] :url_launcher_android:bundleDebugAar (Thread[Execution worker Thread 9,5,main]) completed. Took 0.0 secs.
[        ] Resolve mutations for :url_launcher_android:assembleDebug (Thread[Execution worker Thread 9,5,main]) started.
[        ] Resolve mutations for :url_launcher_android:assembleDebug (Thread[Execution worker Thread 9,5,main]) completed. Took 0.0 secs.
[        ] :url_launcher_android:assembleDebug (Thread[Execution worker Thread 8,5,main]) started.
[        ] > Task :url_launcher_android:assembleDebug UP-TO-DATE
[        ] Skipping task ':url_launcher_android:assembleDebug' as it has no actions.
[        ] :url_launcher_android:assembleDebug (Thread[Execution worker Thread 8,5,main]) completed. Took 0.0 secs.
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 3s
[        ] 133 actionable tasks: 5 executed, 128 up-to-date
[        ] Watched directory hierarchies: [/Users/miquel/dev/projects/google/samples/add_to_app/android_view/flutter_module_using_plugin/.android]
[ +365 ms] Running Gradle task 'assembleDebug'... (completed in 4.0s)
[        ] Calculate SHA1: LocalDirectory: '/Users/miquel/dev/projects/google/samples/add_to_app/android_view/flutter_module_using_plugin/build/host/outputs/apk'/app-debug.apk
[ +449 ms] ✓  Built build/host/outputs/apk/debug/app-debug.apk.
[   +2 ms] Stopping app 'app-debug.apk' on Pixel 5.
[        ] executing: /Users/miquel/Library/Android/sdk/platform-tools/adb -s 09011FDD4009C9 shell am force-stop dev.flutter.example.flutter_module_using_plugin.host
[  +50 ms] executing: /Users/miquel/Library/Android/sdk/platform-tools/adb -s 09011FDD4009C9 shell pm list packages dev.flutter.example.flutter_module_using_plugin.host
[  +49 ms] Installing APK.
[        ] "build/host/outputs/apk/app-debug.apk" does not exist.
[        ] Warning: Failed to install APK.
[        ] Error launching application on Pixel 5.
[   +2 ms] "flutter run" took 7,565ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +1 ms] ensureAnalyticsSent: 1ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

<details><summary>Flutter Doctor</summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-DE)
    • Flutter version 3.7.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /opt/homebrew/Caskroom/flutter/3.0.5/flutter. Consider
      adding /opt/homebrew/Caskroom/flutter/3.0.5/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/miquel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/miquel/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 09011FDD4009C9 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by miquelbeltran** [comment]
fyi @domesticmouse encountered this when doing the Material 3 migration. Not sure if this is the right place to report the issue.

**Comment by domesticmouse** [comment]
Hey @miquelbeltran I'm hoping your recent update of `add_to_app` fixed this?

**Comment by miquelbeltran** [comment]
Yes! This can be closed, also the job runs on CI now
