### ISSUE TITLE
`desktop_photo_search/material` scrolling throwing errors

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#1657]
Hey @Piinks can I get a review on the `desktop_photo_search/material` codebase? Looks like I am using scrolling incorrectly. Halp?

```console
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an
Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController
if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set
ScrollView.primary to true for the Scrollable widget.

When the exception was thrown, this was the stack:
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1564:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:822:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:756:5)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:619:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:467:12)
#8      RawScrollbarState.handleHover (package:flutter/src/widgets/scrollbar.dart:2078:35)
#9      _MaterialScrollbarState.handleHover (package:flutter/src/material/scrollbar.dart:449:11)
#10     RawScrollbarState.build.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:2197:25)
#11     RenderMouseRegion.handleEvent (package:flutter/src/rendering/proxy_box.dart:3266:22)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#18     _invoke1 (dart:ui/hooks.dart:164:13)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)

The AnimationController notifying status listeners was:
  AnimationController#db662(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Piinks** [comment]
It looks like whatever scrolling widget this is, `primary` needs to be set to true. Should be an easy fix. :)

On desktop, the PrimaryScrollController does not attach automatically anymore. 

https://youtu.be/33_0ABjFJUU

https://docs.flutter.dev/release/breaking-changes/primary-scroll-controller-desktop

I just ran into another case of this the other day: https://github.com/flutter/flutter/pull/120728

**Comment by domesticmouse** [comment]
Thank you @Piinks!
