### ISSUE TITLE
`experimental/context_menus`: Test failing on Flutter 3.18.0-7.0.pre.57

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#2110]
Justin, let me know if we should set this experimental app to be `master` channel only so it can be kept up to date with the upstream changes.

```console
❌ /home/runner/work/samples/samples/experimental/context_menus/test/email_button_page_test.dart: Selecting the email address shows a custom button (failed)
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following TestFailure was thrown running a test:
  Expected: exactly 3 matching candidates
    Actual: _TypeWidgetFinder:<Found 4 widgets with type "TextSelectionToolbarTextButton": [
              TextSelectionToolbarTextButton(dependencies: [_InheritedTheme,
  _LocalizationsScope-[GlobalKey#d414e]]),
              TextSelectionToolbarTextButton(dependencies: [_InheritedTheme,
  _LocalizationsScope-[GlobalKey#d414e]]),
              TextSelectionToolbarTextButton(dependencies: [_InheritedTheme,
  _LocalizationsScope-[GlobalKey#d414e]]),
              TextSelectionToolbarTextButton(dependencies: [_InheritedTheme,
  _LocalizationsScope-[GlobalKey#d414e]]),
            ]>
     Which: is too many
  
  When the exception was thrown, this was the stack:
  #4      main.<anonymous closure> (file:///home/runner/work/samples/samples/experimental/context_menus/test/email_button_page_test.dart:59:9)
  <asynchronous suspension>
  #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
  <asynchronous suspension>
  #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  
  This was caught by the test expectation on the following line:
    file:///home/runner/work/samples/samples/experimental/context_menus/test/email_button_page_test.dart line 59
  The test description was:
    Selecting the email address shows a custom button
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  Test failed. See exception logs above.
  The test description was: Selecting the email address shows a custom button
```

**Comment by justinmc** [comment]
This sample can now run on stable. Does that mean it needs to be moved out of `experimental`?

**Comment by domesticmouse** [comment]
Moving this sample from `experimental` to the main directory implies that we will keep the sample always working for Flutter stable release. 

So yes, you can move, but you don't have to.
