### ISSUE TITLE
android_books Build errors 

### ISSUE THREAD

**Issue by birender-s** [flutter/samples#2241]
I searched for existing "issues" related to build errors, could find some (for example [this one](https://github.com/flutter/samples/issues/786)) but they're all closed without enough pointers. Hence creating this one.

I've tried multiple options in last few days but no luck so far. Here are the JDK & Gradle configurations (with Android Studio Hedgehog | 2023.1.1 Patch 1) I've tried and respective errors I'm getting. Looking forward to help/pointers, thanks !
Note: I am able to build other Android Kotlin / Flutter projects (outside this repo) successfully.

**1.  jdk-8.0.402.06-hotspot + gradle-6.5-bin.zip**
Error: Unsupported Java. 
Your build is currently configured to use Java 1.8.0_402 and Gradle 6.5.
Possible solution:
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project
 
**2.  jdk-11.0.22.7-hotspot + gradle-6.5-bin.zip**
Error: Settings file 'C:\Users\birender_singh\Documents\samples-2\add_to_app\books\android_books\settings.gradle' line: 3
A problem occurred evaluating settings 'android_books'.
> C:\Users\birender_singh\Documents\samples-2\add_to_app\books\flutter_module_books\.android\include_flutter.groovy (C:\Users\birender_singh\Documents\samples-2\add_to_app\books\flutter_module_books\.android\include_flutter.groovy)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating settings 'android_books'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
	at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)

**3.  jdk-17.0.10.7-hotspot + gradle-6.5-bin.zip**
Error: Your build is currently configured to use Java 17.0.10 and Gradle 6.5.
Possible solution:
 - Upgrade Gradle wrapper to 7.2 version and re-import the project

**4.  jdk-17.0.10.7-hotspot + gradle-7.2-bin.zip**
Error: Same as in case 2 above

**5. jdk-21.0.3.1-hotspot + gradle-7.2-bin.zip**
Error: Unsupported Java. 
Your build is currently configured to use Java 21.0.3 and Gradle 7.2.

Possible solution:
 - Upgrade Gradle wrapper to 7.6 version and re-import the project

**6. jdk-21.0.3.1-hotspot + gradle-7.6-bin.zip**
Error: Same as in case 2 above

**7. jdk-21.0.3.1-hotspot + gradle-8.2-bin.zip**
Error: Same as in case 2 above

**8. jdk-21.0.3.1-hotspot + gradle-8.3-bin.zip**
Error: Same as in case 2 above

**9. jdk-21.0.3.1-hotspot + gradle-8.5-bin.zip**
Error: Same as in case 2 above

**Comment by birender-s** [comment]
Adding Flutter, Dart Version Info, also flutter doctor output below.
C:\Users\birender_singh>flutter --version
**Flutter 3.19.5** • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (2 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • **Dart 3.3.3** • DevTools 2.31.1

C:\Users\birender_singh>**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22000.2836], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.88.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
