### ISSUE TITLE
multiple_flutters_android  Failed to spawn new JNI connected shell from existing shell.

### ISSUE THREAD

**Issue by zhouxin1233** [flutter/samples#761]
2021-03-09 11:13:34.196 26686-26686/dev.flutter.multipleflutters E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 26686
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.DoubleFlutterActivity}: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at io.flutter.util.Preconditions.checkState(Preconditions.java:52)
        at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:342)
        at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:383)
        at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)
        at dev.flutter.multipleflutters.EngineBindings.<init>(EngineBindings.kt:45)
        at dev.flutter.multipleflutters.DoubleFlutterActivity$topBindings$2.invoke(DoubleFlutterActivity.kt:17)
        at dev.flutter.multipleflutters.DoubleFlutterActivity$topBindings$2.invoke(DoubleFlutterActivity.kt:15)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.getTopBindings(Unknown Source:2)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.onCreate(DoubleFlutterActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:8183)
        at android.app.Activity.performCreate(Activity.java:8167)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by xster** [comment]
Can you run and paste `flutter doctor -v` as well? Seems like a concerning issue but I wasn't able to reproduce it.

**Comment by zhouxin1233** [comment]
> Can you run and paste `flutter doctor -v` as well? Seems like a concerning issue but I wasn't able to reproduce it.
 flutter doctor -v
[✓] Flutter (Channel unknown, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/xiaoxin/Desktop/workspace/Flutter/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xiaoxin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/xiaoxin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

**Comment by zhouxin1233** [comment]
> Can you run and paste `flutter doctor -v` as well? Seems like a concerning issue but I wasn't able to reproduce it.

flutter doctor -v




[✓] Flutter (Channel unknown, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/xiaoxin/Desktop/workspace/Flutter/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xiaoxin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/xiaoxin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

**Comment by zhouxin1233** [comment]
> Can you run and paste `flutter doctor -v` as well? Seems like a concerning issue but I wasn't able to reproduce it.
this is crash video
[https://raw.githubusercontent.com/zhouxin1233/UploadVideo/master/Screen_Recording_20210310-101902_Settings.mp4](url)

**Comment by zerozeus** [comment]
same crash

2021-03-09 17:32:08.850 25070-25070/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 25070
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.DoubleFlutterActivity}: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at io.flutter.util.Preconditions.checkState(Preconditions.java:52)
        at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:342)
        at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:383)
        at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)
        at dev.flutter.multipleflutters.EngineBindings.<init>(EngineBindings.kt:45)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.onCreate(DoubleFlutterActivity.kt:36)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8010) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by AndrewTseZhou** [comment]
I had the same problem

**Comment by branjing** [comment]
The address stored in nativeShellHolderId in Android 11 deveice starts from 0XB4, which is less than 0 in decimal. A 64bis device usually uses its 48 or 52bits of virtual address, so that the address must be positive in decimal. However, I have no idea why a pointer of heap object uses full 64 bits.

**Comment by CarGuo** [comment]
## some with me

Multipleflutters Crash in Special Device  **Mi 11 (Android 11)**  case by `spawnedJNI.nativeShellHolderId < 0` 




1. Run `multiple_flutters_android` in official demo.
2. click `next` until show `DoubleFlutterActivity` .
3. app crash with `spawnedJNI.nativeShellHolderId < 0`

ps:  Crash Device : **Mi 11 (Android 11)** ，workaround with **Redmi 5 Plus（Android 8.1.0）** 、**HuaWei P30pro（Android 10** 、**Virtual Device（Android 11）** 


### Debug Image  `nativeShellHolderId < 0`

![image](https://user-images.githubusercontent.com/10770362/111413033-73669680-8718-11eb-82f2-8dafd693eb5a.png)

![image](https://user-images.githubusercontent.com/10770362/111412412-57162a00-8717-11eb-96c6-a8ea1fdc5f62.png)




### More Info


<details>
  <summary>Log </summary>

```

2021-03-17 11:48:37.208 7788-7788/dev.flutter.multipleflutters E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 7788
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.DoubleFlutterActivity}: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3492)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at io.flutter.util.Preconditions.checkState(Preconditions.java:52)
        at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:342)
        at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:383)
        at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)
        at dev.flutter.multipleflutters.EngineBindings.<init>(EngineBindings.kt:45)
        at dev.flutter.multipleflutters.DoubleFlutterActivity$topBindings$2.invoke(DoubleFlutterActivity.kt:17)
        at dev.flutter.multipleflutters.DoubleFlutterActivity$topBindings$2.invoke(DoubleFlutterActivity.kt:15)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.getTopBindings(Unknown Source:2)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.onCreate(DoubleFlutterActivity.kt:58)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3465)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:7892) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```



```
```



```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 ou

**Comment by xster** [comment]
@RedBrogdon can we turn on the move bot on this repo?

**Comment by CarGuo** [comment]
@xster  I had create same issue in flutter/flutter  [#78389](https://github.com/flutter/flutter/issues/78389#issuecomment-800986483) ，but they tell me the place to file issues related to Flutter examples is in this repository.

**Comment by xster** [comment]
Let's continue in https://github.com/flutter/flutter/issues/78389

**Comment by yxwandroid** [comment]
I had the same problem
