### ISSUE TITLE
multiple_flutters throw exceptions

### ISSUE THREAD

**Issue by Yuiry-IV** [flutter/samples#873]
Hello colleagues, 

I've tried to run multiple_flutters example for Android.  Unfortunately, it trow exceptions for any button: 
```
E/flutter (25543): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method incrementCount on channel multiple-flutters)
E/flutter (25543): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (25543): <asynchronous suspension>
E/flutter (25543):
I/ViewRootImpl@b6a2461[MainActivity](25543): ViewPostIme pointer 0
I/ViewRootImpl@b6a2461[MainActivity](25543): ViewPostIme pointer 1
E/flutter (25543): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method next on channel multiple-flutters)
E/flutter (25543): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (25543): <asynchronous suspension>
E/flutter (25543):
```
Could you please help me to solve this issue? 

My Environment:
```
flutter --version
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (6 months ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

**Comment by gaurav1903** [comment]
Unhandled Exception: MissingPluginException
This error generally occurs when after adding a package to pubspec.yaml ,you don't run 
`flutter pub get ` or after adding and running just do a hot restart .
What you should do is add a package ,run
`flutter pub get `
and then comletely restart the app after terminating it
