### ISSUE TITLE
Android点击next多此必现崩溃

### ISSUE THREAD

**Issue by GraceJoJo** [flutter/samples#876]
Android demo点next必现崩溃：

    Process: dev.flutter.multipleflutters, PID: 18160
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.SingleFlutterActivity}: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3690)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8053)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at io.flutter.util.Preconditions.checkState(Preconditions.java:52)
        at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:342)
        at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:383)
        at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)
        at dev.flutter.multipleflutters.EngineBindings.<init>(EngineBindings.kt:45)
        at dev.flutter.multipleflutters.SingleFlutterActivity$engineBindings$2.invoke(SingleFlutterActivity.kt:16)
        at dev.flutter.multipleflutters.SingleFlutterActivity$engineBindings$2.invoke(SingleFlutterActivity.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dev.flutter.multipleflutters.SingleFlutterActivity.getEngineBindings(Unknown Source:2)
        at dev.flutter.multipleflutters.SingleFlutterActivity.provideFlutterEngine(SingleFlutterActivity.kt:30)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:227)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:155)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
        at dev.flutter.multipleflutters.SingleFlutterActivity.onCreate(SingleFlutterActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:8143)
        at android.app.Activity.performCreate(Activity.java:8115)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3503)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3690) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8053)

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @GraceJoJo. This looks similar to a report we've had before, #761.

Can you provide a little more detail about what you were doing when you saw this issue? In particular, I'd love to know what Android version you're running, which app you were running, and what the output of `flutter doctor -v` looks like on your machine.

@gaaclarke or @xster, it looks like there was an SDK change to address a bug that would cause this exception (https://github.com/flutter/flutter/issues/78389). Is that still in the process of making its way to stable, or would it have come out in the 2.2 release?
