### ISSUE TITLE
testing_app fails on macOS

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#999]
All of the integration tests fail when I run them on a `macOS` device:

```
flutter test integration_test -d macos
```

<details>
<summary>
Logs
</summary>

```
flutter test integration_test -d macos
Downloading darwin-x64/FlutterMacOS.framework tools...           2,929ms
Downloading darwin-x64-profile/FlutterMacOS.framework tools...      1,754ms
Downloading darwin-x64-profile tools...                            665ms
Downloading darwin-x64-release/FlutterMacOS.framework tools...      1,721ms
Downloading darwin-x64-release tools...                            727ms
00:05 +0: ...hn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart     R00:06 +0: ...hn/code/github/flutter/samples/testing_app/integration_test/perf_test.d 1,249ms
00:14 +0: ...hn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart     B--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:28255B09-AB6E-5AA0-8047-CDCAE6267EA0 }
{ platform:macOS, name:Any Mac }
00:41 +0: ...hn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart     
00:47 +0: /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart: Testing App Performance Tests Scrolling test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SocketException was thrown running a test:
Connection failed (OS Error: Operation not permitted, errno = 1), address = localhost, port = 59947
 
When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1808:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2027:22)
#4      Socket.startConnect (dart:io/socket.dart:784:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#11     WebSocket.connect (dart:_http/websocket.dart:360:22)
#12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#13     IntegrationTestWidgetsFlutterBinding.enableTimeline (package:integration_test/integration_test.dart:247:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
 
The test description was:
  Scrolling test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:47 +0 -1: /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart: Testing App Performance Tests Scrolling test [E]
  Test failed. See exception logs above.
  The test description was: Scrolling test
  
00:49 +0 -1: /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart: Testing App Performance Tests Favorites operations test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SocketException was thrown running a test:
Connection failed (OS Error: Operation not permitted, errno = 1), address = localhost, port = 59947
 
When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1808:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2027:22)
#4      Socket.startConnect (dart:io/socket.dart:784:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#11     WebSocket.connect (dart:_http/websocket.dart:360:22)
#12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#13     IntegrationTestWidgetsFlutterBinding.enableTimeline (package:integration_test/integration_test.dart:247:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
 
The test description was:
  Favorites operations test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:49 +0 -2: /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/perf_test.dart: Testing App Performance Tests Favorites operations test [E]
  Test failed. See exception logs above.
  The test description was: Favorites operations test
  
00:49 +0 -2: ...ithub/flutter/samples/testing_app/integration_test/state_mgmt_test.dart     R00:50 +0 -2: ...ithub/flutter/samples/testing_app/integration_test/state_mgmt_test.d 1,131ms
00:52 +0 -2: ...ithub/flutter/samples/testing_app/integration_test/state_mgmt_test.dart     B--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:28255B09-AB6E-5AA0-8047-CDCAE6267EA0 }
{ platform:macOS, name:Any Mac }
01:06 +0 -2: ...ithub/flutter/samples/testing_app/integration_test/state_mgmt_test.dart     
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
01:06 +0 -3: loading /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/state_mgmt_test.dart [E]
  TestDeviceException(Unable to start the app on the device.)
  package:flutter_tools/src/test/integration_test_device.dart 61:7  IntegrationTestTestDevice.start
  
01:06 +0 -3: .../code/github/flutter/samples/testing_app/integration_test/app_test.dart     R01:01:08 +0 -3: .../code/github/flutter/samples/testing_app/integration_test/app_test.d 1,186ms
01:08 +0 -3: loading /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/state_mgmt_test.dart [E]
  Bad state: Cannot add new events after calling close
  dart:async/broadcast_stream_controller.dart 243:24  _BroadcastStreamController.add
  dart:async/zone.dart 1436:47                        _rootRunUnary
  dart:async/zone.dart 1335:19                        _CustomZone.runUnary
  dart:async/zone.dart 1244:7                         _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 341:11                  _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                   _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 733:19            _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 607:7             _StreamController._add
  dart:async/stream_controller.dart 554:5             _StreamController.add
  dart:io-patch/socket_patch.dart 2302:41             _Socket._onData
  dart:async/zone.dart 1444:13                        _rootRunUnary
  dart:async/zone.dart 1335:19                        _CustomZone.runUnary
  dart:async/zone.dart 1244:7                         _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 341:11                  _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                   _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 733:19            _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 607:7             _StreamController._add
  dart:async/stream_controller.dart 554:5             _StreamController.add
  dart:io-patch/socket_patch.dart 1830:33             new _RawSocket.<fn>
  dart:io-patch/socket_patch.dart 1314:14             _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 40:21            _microtaskLoop
  dart:async/schedule_microtask.dart 49:5             _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 122:13        _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 193:5         _RawReceivePortImpl._handleMessage
  
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:28255B09-AB6E-5AA0-8047-CDCAE6267EA0 }
{ platform:macOS, name:Any Mac }
Building macOS application...                                           
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
01:23 +0 -4: loading /Users/ryjohn/code/github/flutter/samples/testing_app/integration_test/app_test.dart [E]
  TestDeviceException(Unable to start the app on the device.)
  package:flutter_tools/src/test/integration_test_device.dart 61:7  IntegrationTestTestDevice.start
  
01:23 +0 -4: Some tests failed.
```

</details>

```
flutter --version
Flutter 2.10.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 628f0e3f3a (9 days ago) • 2022-01-11 19:50:05 -0600
Engine • revision 63ca99584a
Tools • Dart 2.16.0 (build 2.16.0-134.1.beta) • DevTools 2.9.2
```

**Comment by domesticmouse** [comment]
Hey @cbracken, another one for ya

**Comment by ericwindmill** [comment]
This seems to be an issue with flutter/flutter, so I'm closing this ticket. See [flutter/flutter #101031](https://github.com/flutter/flutter/issues/101031)
